/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package principal;

/**
 *
 * @author 123
 */
public class mdiPrincipal extends javax.swing.JFrame {
    
private jpFormulario1 objFormulario1 = new jpFormulario1();
private jpFormulario2 objFormulario2 = new jpFormulario2(); 
private jpFormulario3 objFormulario3 = new jpFormulario3();
private jpFormulario4 objFormulario4 = new jpFormulario4(); 
private jpFormulario5 objFormulario5 = new jpFormulario5();
private jpFormulario6 objFormulario6 = new jpFormulario6(); 

private void inicializarFormularios() {
        
    jifFormulario1.setContentPane(objFormulario1);
    objFormulario1.setSize(300,300);
    jifFormulario1.setSize(300,300);
    
    jifFormulario2.setContentPane(objFormulario2);
    objFormulario2.setSize(300,300);
    jifFormulario2.setSize(300,300);
    
    jifFormulario3.setContentPane(objFormulario3);
    objFormulario3.setSize(300,300);
    jifFormulario3.setSize(300,300);
    
    jifFormulario4.setContentPane(objFormulario4);
    objFormulario4.setSize(300,300);
    jifFormulario4.setSize(300,300);
    
    jifFormulario5.setContentPane(objFormulario5);
    objFormulario5.setSize(300,300);
    jifFormulario5.setSize(300,300);
    
    jifFormulario6.setContentPane(objFormulario6);
    objFormulario6.setSize(300,300);
    jifFormulario6.setSize(300,300);
}

    
    public mdiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifFormulario1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtRadio = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        txtPerimetro = new javax.swing.JTextField();
        jifFormulario2 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnCalcular2 = new javax.swing.JButton();
        btnLimpiar2 = new javax.swing.JButton();
        txtBase = new javax.swing.JTextField();
        txtArea2 = new javax.swing.JTextField();
        txtAltura = new javax.swing.JTextField();
        txtPerimetro2 = new javax.swing.JTextField();
        jifFormulario3 = new javax.swing.JInternalFrame();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnCalcular3 = new javax.swing.JButton();
        btnLimpiar3 = new javax.swing.JButton();
        txtLado = new javax.swing.JTextField();
        txtPerimetro3 = new javax.swing.JTextField();
        txtArea3 = new javax.swing.JTextField();
        jifFormulario4 = new javax.swing.JInternalFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtBase4 = new javax.swing.JTextField();
        txtAltura4 = new javax.swing.JTextField();
        txtArea4 = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtPerimetro4 = new javax.swing.JTextField();
        btnCalcular4 = new javax.swing.JButton();
        btnLimpiar4 = new javax.swing.JButton();
        jifFormulario5 = new javax.swing.JInternalFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtD = new javax.swing.JTextField();
        txtd = new javax.swing.JTextField();
        txtLado5 = new javax.swing.JTextField();
        txtArea5 = new javax.swing.JTextField();
        txtPerimetro5 = new javax.swing.JTextField();
        btnCalcular5 = new javax.swing.JButton();
        btnLimpiar5 = new javax.swing.JButton();
        jifFormulario6 = new javax.swing.JInternalFrame();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtA = new javax.swing.JTextField();
        txtC = new javax.swing.JTextField();
        txtB = new javax.swing.JTextField();
        txtD6 = new javax.swing.JTextField();
        txtH = new javax.swing.JTextField();
        btnCalcular6 = new javax.swing.JButton();
        btnLimpiar6 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtArea6 = new javax.swing.JTextField();
        txtPerimetro6 = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jmiFormulario1 = new javax.swing.JMenuItem();
        jmiFormulario2 = new javax.swing.JMenuItem();
        jmiFormulario3 = new javax.swing.JMenuItem();
        jmiFormulario4 = new javax.swing.JMenuItem();
        jmiFormulario5 = new javax.swing.JMenuItem();
        jmiFormulario6 = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifFormulario1.setClosable(true);
        jifFormulario1.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormulario1.setTitle("Circulo");
        jifFormulario1.setVisible(false);

        jLabel1.setText("Radio");

        jLabel2.setText("Area");

        jLabel4.setText("Perimetro");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAreaActionPerformed(evt);
            }
        });

        txtPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerimetroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifFormulario1Layout = new javax.swing.GroupLayout(jifFormulario1.getContentPane());
        jifFormulario1.getContentPane().setLayout(jifFormulario1Layout);
        jifFormulario1Layout.setHorizontalGroup(
            jifFormulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario1Layout.createSequentialGroup()
                .addGroup(jifFormulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jifFormulario1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jifFormulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(6, 6, Short.MAX_VALUE)
                        .addGroup(jifFormulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(txtArea)
                            .addComponent(txtPerimetro)))
                    .addGroup(jifFormulario1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnCalcular)
                        .addGap(28, 28, 28)
                        .addComponent(btnLimpiar)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jifFormulario1Layout.setVerticalGroup(
            jifFormulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jifFormulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jifFormulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jifFormulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jifFormulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar))
                .addGap(41, 41, 41))
        );

        desktopPane.add(jifFormulario1);
        jifFormulario1.setBounds(170, 60, 340, 280);

        jifFormulario2.setClosable(true);
        jifFormulario2.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormulario2.setTitle("Rectangulo");
        jifFormulario2.setVisible(false);

        jLabel3.setText("Base");

        jLabel5.setText("Altura");

        jLabel6.setText("Area");

        jLabel7.setText("Perimetro");

        btnCalcular2.setText("Calcular");
        btnCalcular2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular2ActionPerformed(evt);
            }
        });

        btnLimpiar2.setText("Limpiar");
        btnLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar2ActionPerformed(evt);
            }
        });

        txtArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArea2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifFormulario2Layout = new javax.swing.GroupLayout(jifFormulario2.getContentPane());
        jifFormulario2.getContentPane().setLayout(jifFormulario2Layout);
        jifFormulario2Layout.setHorizontalGroup(
            jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifFormulario2Layout.createSequentialGroup()
                        .addGroup(jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAltura)
                            .addComponent(txtBase)
                            .addComponent(txtArea2)
                            .addComponent(txtPerimetro2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
                    .addGroup(jifFormulario2Layout.createSequentialGroup()
                        .addComponent(btnCalcular2)
                        .addGap(30, 30, 30)
                        .addComponent(btnLimpiar2)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jifFormulario2Layout.setVerticalGroup(
            jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPerimetro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jifFormulario2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular2)
                    .addComponent(btnLimpiar2))
                .addGap(20, 20, 20))
        );

        desktopPane.add(jifFormulario2);
        jifFormulario2.setBounds(210, 50, 340, 270);

        jifFormulario3.setClosable(true);
        jifFormulario3.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormulario3.setTitle("Cuadrado");
        jifFormulario3.setVisible(false);

        jLabel8.setText("Lado");

        jLabel9.setText("Area");

        jLabel10.setText("Perimetro");

        btnCalcular3.setText("Calcular");
        btnCalcular3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular3ActionPerformed(evt);
            }
        });

        btnLimpiar3.setText("Limpiar");
        btnLimpiar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifFormulario3Layout = new javax.swing.GroupLayout(jifFormulario3.getContentPane());
        jifFormulario3.getContentPane().setLayout(jifFormulario3Layout);
        jifFormulario3Layout.setHorizontalGroup(
            jifFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario3Layout.createSequentialGroup()
                .addGroup(jifFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jifFormulario3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jifFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jifFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerimetro3)
                            .addComponent(txtLado)
                            .addComponent(txtArea3)))
                    .addGroup(jifFormulario3Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnCalcular3)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar3)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jifFormulario3Layout.setVerticalGroup(
            jifFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jifFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtArea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jifFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPerimetro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jifFormulario3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular3)
                    .addComponent(btnLimpiar3))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        desktopPane.add(jifFormulario3);
        jifFormulario3.setBounds(210, 50, 340, 310);

        jifFormulario4.setClosable(true);
        jifFormulario4.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormulario4.setTitle("Triangulo Rectangulo");
        jifFormulario4.setVisible(false);

        jLabel11.setText("Base");

        jLabel12.setText("Altura");

        jLabel13.setText("Area");

        jLabel14.setText("Perimetro");

        jLabel15.setText("Tipo");

        txtAltura4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltura4ActionPerformed(evt);
            }
        });

        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });

        btnCalcular4.setText("Calcular");
        btnCalcular4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular4ActionPerformed(evt);
            }
        });

        btnLimpiar4.setText("Limpiar");
        btnLimpiar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifFormulario4Layout = new javax.swing.GroupLayout(jifFormulario4.getContentPane());
        jifFormulario4.getContentPane().setLayout(jifFormulario4Layout);
        jifFormulario4Layout.setHorizontalGroup(
            jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jifFormulario4Layout.createSequentialGroup()
                        .addComponent(btnCalcular4)
                        .addGap(37, 37, 37)
                        .addComponent(btnLimpiar4))
                    .addGroup(jifFormulario4Layout.createSequentialGroup()
                        .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jifFormulario4Layout.createSequentialGroup()
                                .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGap(20, 20, 20)))
                        .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jifFormulario4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAltura4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBase4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jifFormulario4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPerimetro4)
                                    .addComponent(txtTipo))))))
                .addGap(2, 2, 2))
        );
        jifFormulario4Layout.setVerticalGroup(
            jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtBase4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtAltura4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtArea4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPerimetro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(21, 21, 21)
                .addGroup(jifFormulario4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular4)
                    .addComponent(btnLimpiar4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(jifFormulario4);
        jifFormulario4.setBounds(210, 50, 320, 330);

        jifFormulario5.setClosable(true);
        jifFormulario5.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormulario5.setTitle("Rombo");
        jifFormulario5.setVisible(false);

        jLabel16.setText("D");

        jLabel17.setText("d");

        jLabel18.setText("Lado");

        jLabel19.setText("Area");

        jLabel20.setText("Perimetro");

        txtD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDActionPerformed(evt);
            }
        });

        txtPerimetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerimetro5ActionPerformed(evt);
            }
        });

        btnCalcular5.setText("Calcular");
        btnCalcular5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular5ActionPerformed(evt);
            }
        });

        btnLimpiar5.setText("Limpiar");
        btnLimpiar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifFormulario5Layout = new javax.swing.GroupLayout(jifFormulario5.getContentPane());
        jifFormulario5.getContentPane().setLayout(jifFormulario5Layout);
        jifFormulario5Layout.setHorizontalGroup(
            jifFormulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jifFormulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(33, 33, 33)
                .addGroup(jifFormulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtLado5)
                    .addComponent(txtD)
                    .addComponent(txtd)
                    .addComponent(txtArea5)
                    .addComponent(txtPerimetro5, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
            .addGroup(jifFormulario5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnCalcular5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpiar5))
        );
        jifFormulario5Layout.setVerticalGroup(
            jifFormulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jifFormulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifFormulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifFormulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(txtLado5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifFormulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtArea5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jifFormulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtPerimetro5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jifFormulario5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular5)
                    .addComponent(btnLimpiar5))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        desktopPane.add(jifFormulario5);
        jifFormulario5.setBounds(210, 50, 300, 290);

        jifFormulario6.setClosable(true);
        jifFormulario6.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormulario6.setTitle("Trapecio");
        jifFormulario6.setToolTipText("");
        jifFormulario6.setVisible(false);

        jLabel21.setText("A");

        jLabel22.setText("D");

        jLabel23.setText("B");

        jLabel24.setText("C");

        jLabel25.setText("H");

        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });

        txtD6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtD6ActionPerformed(evt);
            }
        });

        btnCalcular6.setText("Calcular");
        btnCalcular6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular6ActionPerformed(evt);
            }
        });

        btnLimpiar6.setText("Limpiar");
        btnLimpiar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar6ActionPerformed(evt);
            }
        });

        jLabel26.setText("Area");

        jLabel27.setText("Perimetro");

        txtArea6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArea6ActionPerformed(evt);
            }
        });

        txtPerimetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerimetro6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jifFormulario6Layout = new javax.swing.GroupLayout(jifFormulario6.getContentPane());
        jifFormulario6.getContentPane().setLayout(jifFormulario6Layout);
        jifFormulario6Layout.setHorizontalGroup(
            jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jifFormulario6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnCalcular6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btnLimpiar6)
                        .addGap(11, 11, 11))
                    .addGroup(jifFormulario6Layout.createSequentialGroup()
                        .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel25)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(56, 56, 56)
                        .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtA)
                            .addComponent(txtB)
                            .addComponent(txtC)
                            .addComponent(txtH)
                            .addComponent(txtD6)
                            .addComponent(txtArea6)
                            .addComponent(txtPerimetro6))))
                .addGap(148, 148, 148))
        );
        jifFormulario6Layout.setVerticalGroup(
            jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jifFormulario6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtD6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtArea6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtPerimetro6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jifFormulario6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular6)
                    .addComponent(btnLimpiar6))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        desktopPane.add(jifFormulario6);
        jifFormulario6.setBounds(120, 30, 450, 420);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Archivo");

        jmiFormulario1.setMnemonic('o');
        jmiFormulario1.setText("Formulario 1 ");
        jmiFormulario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormulario1ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormulario1);

        jmiFormulario2.setMnemonic('s');
        jmiFormulario2.setText("Formulario 2");
        jmiFormulario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormulario2ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormulario2);

        jmiFormulario3.setText("Formulario 3");
        jmiFormulario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormulario3ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormulario3);

        jmiFormulario4.setText("Formulario 4");
        jmiFormulario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormulario4ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormulario4);

        jmiFormulario5.setText("Formulario 5");
        jmiFormulario5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormulario5ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormulario5);

        jmiFormulario6.setText("Formulario 6");
        jmiFormulario6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormulario6ActionPerformed(evt);
            }
        });
        fileMenu.add(jmiFormulario6);

        jmiSalir.setMnemonic('x');
        jmiSalir.setText("Exit");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        fileMenu.add(jmiSalir);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiFormulario6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormulario6ActionPerformed
        jifFormulario6.setVisible(true);
    }//GEN-LAST:event_jmiFormulario6ActionPerformed

    private void jmiFormulario5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormulario5ActionPerformed
        jifFormulario5.setVisible(true);
    }//GEN-LAST:event_jmiFormulario5ActionPerformed

    private void jmiFormulario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormulario4ActionPerformed
        jifFormulario4.setVisible(true);
    }//GEN-LAST:event_jmiFormulario4ActionPerformed

    private void jmiFormulario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormulario3ActionPerformed
        jifFormulario3.setVisible(true);
    }//GEN-LAST:event_jmiFormulario3ActionPerformed

    private void jmiFormulario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormulario2ActionPerformed
        jifFormulario2.setVisible(true);
    }//GEN-LAST:event_jmiFormulario2ActionPerformed

    private void jmiFormulario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormulario1ActionPerformed
        jifFormulario1.setVisible(true);
    }//GEN-LAST:event_jmiFormulario1ActionPerformed

    private void txtPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerimetroActionPerformed

    private void txtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAreaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        int radio;
       double area, perimetro;
       radio = Integer.parseInt(txtRadio.getText());
       Circulo figura1 = new Circulo(radio);
       area = figura1.calcularArea();
       perimetro = figura1.calcularPerimetro();
       txtArea.setText(String.valueOf(area));
       txtPerimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtRadio.setText(Circulo.limpiarCampo());
        txtArea.setText(Circulo.limpiarCampo());
        txtPerimetro.setText(Circulo.limpiarCampo());
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArea2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArea2ActionPerformed

    private void btnCalcular2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular2ActionPerformed
       int base, altura;
       double area, perimetro;
       base = Integer.parseInt(txtBase.getText());
       altura = Integer.parseInt(txtAltura.getText());
       Rectangulo figura2 = new Rectangulo(base, altura);
       area = figura2.calcularArea();
       perimetro = figura2.calcularPerimetro();
       txtArea2.setText(String.valueOf(area));
       txtPerimetro2.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnCalcular2ActionPerformed

    private void btnLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar2ActionPerformed
         txtBase.setText(Rectangulo.limpiarCampo());
         txtAltura.setText(Rectangulo.limpiarCampo());
        txtArea2.setText(Rectangulo.limpiarCampo());
        txtPerimetro2.setText(Rectangulo.limpiarCampo());
    }//GEN-LAST:event_btnLimpiar2ActionPerformed

    private void btnCalcular3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular3ActionPerformed
       int lado;
       double area, perimetro;
       lado = Integer.parseInt(txtLado.getText());
       Cuadrado figura3 = new Cuadrado(lado);
       area = figura3.calcularArea();
       perimetro = figura3.calcularPerimetro();
       txtArea3.setText(String.valueOf(area));
       txtPerimetro3.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnCalcular3ActionPerformed

    private void btnLimpiar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar3ActionPerformed
        txtLado.setText(Cuadrado.limpiarCampo());
        txtArea3.setText(Cuadrado.limpiarCampo());
        txtPerimetro3.setText(Cuadrado.limpiarCampo());
    }//GEN-LAST:event_btnLimpiar3ActionPerformed

    private void txtAltura4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltura4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltura4ActionPerformed

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoActionPerformed

    private void btnCalcular4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular4ActionPerformed
       int base, altura;
       double area, perimetro;
       
       base = Integer.parseInt(txtBase4.getText());
       altura = Integer.parseInt(txtAltura4.getText());
       TrianguloRectangulo figura4 = new TrianguloRectangulo(base, altura);
       area = figura4.calcularArea();
       perimetro = figura4.calcularPerimetro();
       txtArea4.setText(String.valueOf(area));
       txtPerimetro4.setText(String.valueOf(perimetro));
       txtTipo.setText(figura4.determinarTipoTriangulo());
    }//GEN-LAST:event_btnCalcular4ActionPerformed

    private void btnLimpiar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar4ActionPerformed
        txtBase4.setText(TrianguloRectangulo.limpiarCampo());
        txtAltura4.setText(TrianguloRectangulo.limpiarCampo());
        txtArea4.setText(TrianguloRectangulo.limpiarCampo());
        txtPerimetro4.setText(TrianguloRectangulo.limpiarCampo());
        txtTipo.setText(TrianguloRectangulo.limpiarCampo());
    }//GEN-LAST:event_btnLimpiar4ActionPerformed

    private void txtPerimetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerimetro5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerimetro5ActionPerformed

    private void txtDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDActionPerformed

    private void btnLimpiar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar5ActionPerformed
        txtD.setText(Rombo.limpiarCampo());
        txtd.setText(Rombo.limpiarCampo());
        txtLado5.setText(Rombo.limpiarCampo());
        txtArea5.setText(Rombo.limpiarCampo());
        txtPerimetro5.setText(Rombo.limpiarCampo());
    }//GEN-LAST:event_btnLimpiar5ActionPerformed

    private void btnCalcular5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular5ActionPerformed
       int lado, D, d;
       double area, perimetro;
       D = Integer.parseInt(txtD.getText());
       d = Integer.parseInt(txtd.getText());
       lado = Integer.parseInt(txtLado5.getText());
       
       Rombo figura5 = new Rombo(D, d, lado);
       area = figura5.calcularArea();
       perimetro = figura5.calcularPerimetro();
       txtArea5.setText(String.valueOf(area));
       txtPerimetro5.setText(String.valueOf(perimetro));
       
    }//GEN-LAST:event_btnCalcular5ActionPerformed

    private void txtD6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtD6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtD6ActionPerformed

    private void txtArea6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArea6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArea6ActionPerformed

    private void btnCalcular6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular6ActionPerformed
       int a, b, c,d, h;
       double area, perimetro;
       a = Integer.parseInt(txtA.getText());
       b = Integer.parseInt(txtB.getText());
       c = Integer.parseInt(txtC.getText());
       d = Integer.parseInt(txtD6.getText());
       h = Integer.parseInt(txtH.getText());
       
       Trapecio figura6 = new Trapecio(a, b, c, d, h);
       area = figura6.calcularArea();
       perimetro = figura6.calcularPerimetro();
       txtArea6.setText(String.valueOf(area));
       txtPerimetro6.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnCalcular6ActionPerformed

    private void btnLimpiar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar6ActionPerformed
        txtA.setText(Trapecio.limpiarCampo());
        txtB.setText(Trapecio.limpiarCampo());
        txtC.setText(Trapecio.limpiarCampo());
        txtD.setText(Trapecio.limpiarCampo());
        txtH.setText(Trapecio.limpiarCampo());
        txtArea6.setText(Trapecio.limpiarCampo());
        txtPerimetro6.setText(Trapecio.limpiarCampo());
    }//GEN-LAST:event_btnLimpiar6ActionPerformed

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCActionPerformed

    private void txtPerimetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerimetro6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerimetro6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcular2;
    private javax.swing.JButton btnCalcular3;
    private javax.swing.JButton btnCalcular4;
    private javax.swing.JButton btnCalcular5;
    private javax.swing.JButton btnCalcular6;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar2;
    private javax.swing.JButton btnLimpiar3;
    private javax.swing.JButton btnLimpiar4;
    private javax.swing.JButton btnLimpiar5;
    private javax.swing.JButton btnLimpiar6;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JInternalFrame jifFormulario1;
    private javax.swing.JInternalFrame jifFormulario2;
    private javax.swing.JInternalFrame jifFormulario3;
    private javax.swing.JInternalFrame jifFormulario4;
    private javax.swing.JInternalFrame jifFormulario5;
    private javax.swing.JInternalFrame jifFormulario6;
    private javax.swing.JMenuItem jmiFormulario1;
    private javax.swing.JMenuItem jmiFormulario2;
    private javax.swing.JMenuItem jmiFormulario3;
    private javax.swing.JMenuItem jmiFormulario4;
    private javax.swing.JMenuItem jmiFormulario5;
    private javax.swing.JMenuItem jmiFormulario6;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField txtA;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAltura4;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtArea2;
    private javax.swing.JTextField txtArea3;
    private javax.swing.JTextField txtArea4;
    private javax.swing.JTextField txtArea5;
    private javax.swing.JTextField txtArea6;
    private javax.swing.JTextField txtB;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtBase4;
    private javax.swing.JTextField txtC;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextField txtD6;
    private javax.swing.JTextField txtH;
    private javax.swing.JTextField txtLado;
    private javax.swing.JTextField txtLado5;
    private javax.swing.JTextField txtPerimetro;
    private javax.swing.JTextField txtPerimetro2;
    private javax.swing.JTextField txtPerimetro3;
    private javax.swing.JTextField txtPerimetro4;
    private javax.swing.JTextField txtPerimetro5;
    private javax.swing.JTextField txtPerimetro6;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtd;
    // End of variables declaration//GEN-END:variables

}
